version: "3.8"
services:
    db:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: trading-analytics
        ports:
            - 3306:3306
        healthcheck:
            test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
            timeout: 2s
            retries: 10
    backend:
        image: docker.io/bitnami/laravel:10
        environment:
            DB_HOST: db
            DB_PORT: 3306
            DB_USERNAME: root
            DB_DATABASE: trading-analytics
            DB_PASSWORD: root
        ports:
            - "8000:8000"
            - "80:80"
            - "5173:5173"
        volumes:
            - './:/app'
        command: sh -c '(php artisan migrate && npm install) && ("/opt/bitnami/scripts/laravel/run.sh" & npm run dev)'
        depends_on:
            db:
                condition: service_healthy
